#!/bin/bash

# args
dev=$1
file=$2
str=$3

# libs
if ! grep zway <<< $PATH >/dev/null; then
  export PATH=$PATH:$(lib-path zway)
fi

# initialise
path=$(dev-path $dev)

# check
[ -n "$path" ] && [ -n "$str" ] || exit 1
grep -w $(zwy-str wake) <<< $str >/dev/null || exit 1
chk-dir $path/wake || mkdir -p $path/wake

# main
id=$(zwy-id $str)
node=(${id//./ })

ep=$(jq -c ".\"$str\".value" $file)
[ -n "$ep" ] || exit 1

file=$path/wake/$node
chk-file $file && [[ $(file-age $file) -lt 2 ]] && exit 0

url=$(zwy-url $dev $node.0.132.data.interval.value)
int=$(http-get $url)

chk-int $int || exit 1
next=$((ep+int))
echo node-$node, is awake
echo $next > $file
