#!/bin/bash

# args
dev=$1

# libs
if ! grep zway <<< $PATH >/dev/null; then
  export PATH=$PATH:$(lib-path zway)
fi

# path
path=$(zwy-path)
prt=$(dev-prt $dev)

# check
[[ $# -eq 1 ]] && [ -n "$path" ] && [ -c $prt ] || exit 1

# functions
end() {
	kill $zwy 2>/dev/null
}

fail() {
  if [[ $# -eq 1 ]]; then
    fail=$1
  else
    ((fail++))
  fi
}

# traps
trap end SIGTERM SIGINT SIGHUP

# main
cd $path

# config
cfg=$(zwy-cfg $dev file)
[ -z "$cfg" ] && exit 1

# http
tcp=$(zwy-tcp $dev)
[ -z "$tcp" ] && exit 1

# existing
for pid in $(pgrep -f "$cfg"); do
	kill $pid
done
fail 0
while chk-tcp $tcp; do
	fail
	sleep 1
  [[ $fail -ge 5 ]] && exit 1
done

# server
LD_LIBRARY_PATH=libs ./z-way-server -c $cfg &>/dev/null &
zwy=$!
sleep 3

# monitor
fail 0
while chk-pid $PPID; do
  sleep 1
	[ -c $prt ] && fail 0 || fail
  chk-pid $zwy || exit 1
  [[ $fail -ge 5 ]] && break
done
end
