#!/bin/bash

# check
[[ $# -eq 1 ]] || exit 1

# main
dev=0x${1:2:2}${1:4:2}
id=${1:8:4}
val=$((0x${1:12:4}))
[[ $val -gt 32767 ]] && val=$((32767-val))
val=$(flt-rnd $(flt-math $val x 0.1) 1)
echo $dev:$id=$val
