#!/bin/bash

# check
[ -n "$1" ] || exit 1

# table
table=points

# sql
if chk-int $1; then
	sql="DELETE FROM $table WHERE id=\"$1\""
else
	sql="DELETE FROM $table WHERE point=\"$1\""
fi

# main
bms-sql $sql
