#!/bin/bash

# check
[ -n "$1" ] || exit 1

# table
table=points

# sql
if [[ $# -eq 1 ]]; then
	if chk-int $1; then
		sql="SELECT value FROM $table WHERE id=\"$1\""
	else
		exit 1
	fi
else
	sql="SELECT value FROM $table WHERE device=\"$1\" AND point=\"$2\""
fi

# main
bms-sql $sql 2>/dev/null
