#!/bin/bash

# initialise
table=data

# functions
epoch() {
	int=$(bms-sql SELECT \`purge\` FROM points WHERE alias=\"$1\")
	if [[ $int -gt 0 ]]; then
		sec=$((int*86400))
		ep=$(get-ep)
		echo $((ep-sec))
	fi
}

purge() {
	if [ -n "$epoch" ]; then
		bms-sql "SELECT id FROM $table WHERE alias=\"$1\" AND last < $epoch" | {
			n=0
			while read id; do
				[ -n "$ids" ] && ids+=,
				ids+=$id
				((n++))
			done
			if [[ $n -gt 0 ]]; then
				bms-sql "DELETE FROM $table WHERE id IN ($ids)"
				echo deleted $n records for $1
			fi
		}
	fi
}

# main
if [[ $# -eq 1 ]]; then
	purge $1
else
	for alias in $(bms-sql SELECT DISTINCT alias FROM $table); do
		purge $alias
	done
fi
